name: Keep Alive

on:
  schedule:
    - cron: "0 8 1 * *"  # Primer día de cada mes a las 08:00 UTC
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Keep alive
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git commit --allow-empty -m "chore: keep workflows active"
          git push
